# - name: Ansible Copy Local to Remote
#   hosts: prod
#   vars:
#     src_path: "{{ workspace_path }}/webapp/target/webapp.war"
#     dest_path: "/opt/tomcat/webapps"
#     config_file_src_path: "{{ hosts }}-config.yaml"
#     config_file_dest_path: "/home"
#   tasks:
#     - name: copying file with playbook
#       become: true
#       copy:
#         src: "{{ src_path }}"
#         dest: "{{ dest_path }}"
#         owner: ansadmin
#         group: ansadmin
#         mode: 0644

- name: Ansible Copy Local to Remote
  hosts: prod
  vars:
    src_path: "/var/lib/jenkins/workspace/Mou-CICD-ProjectPipeline/webapp/target/webapp.war"
    dest_path: "/opt/tomcat/webapps/webapp.war"
  tasks:
    - name: Copy WAR to Tomcat
      become: true
      copy:
        src: "{{ src_path }}"
        dest: "{{ dest_path }}"
        owner: ansadmin
        group: ansadmin
        mode: 0644

    - name: Restart Tomcat
      become: true
      systemd:
        name: tomcat
        state: restarted
